name: LG
version: 1.4.1
author: Neyuux_
main: fr.neyuux.lgthierce.LG
softdepend: [NeyGin_Core]
commands:
  ankou:
    description: Commande de l'Ankou
#  end:
#    description: Redemarre la map
#    permission: end.use
#  spec:
#    description: Commande de spectateur
#    aliases: [s, spectateur, sp, spectateurs, spect]