package fr.neyuux.lgthierce;

public enum DisplayState {

	DISTRIBUTION_DES_ROLES, LECTURE_DES_ROLES, TOMBEE_DE_LA_NUIT, DEMARRAGE_DE_LA_NUIT, NUIT_VOLEUR, NUIT_CUPIDON, NUIT_ES, NUIT_CL, NUIT_JUMEAU, NUIT_NOCTA, NUIT_COMEDIEN, NUIT_VOVO, NUIT_VOVO_D$AURA, NUIT_ENCHANT, NUIT_DÉTEC, NUIT_RENARD, NUIT_PACIF, NUIT_FDJ, NUIT_GDC, NUIT_SALVA, NUIT_LG, NUIT_IPDL, NUIT_GML, NUIT_LGB, NUIT_PF2, NUIT_SOSO, NUIT_PRÊTRE , NUIT_NÉCRO, NUIT_VG, NUIT_DICTA, NUIT_MAMIE, NUIT_CORBEAU, NUIT_JDF, NUIT_PYRO, NUIT_SOEUR, NUIT_FRERE, ANNONCES_DES_MORTS_NUIT, ANNONCES_DES_MORTS_JOUR, CHOIX_SERVANTE, ELECTIONS_DU_MAIRE, VOTE, VOTE_MAIRE, VOTE2, TIR_CHASSEUR, CHOIX_FOSSOYEUR

}
