name: LG
version: beta2.0.0
author: Neyuux_
main: fr.neyuux.refont.lg.LG
softdepend: [NeyGin_Core]
commands:
  lg:
    description: Commande plugin LG
#  end:
#    description: Redemarre la map
#    permission: end.use
#  spec:
#    description: Commande de spectateur
#    aliases: [s, spectateur, sp, spectateurs, spect]